"""Add conversion models for Super Admin feature

Revision ID: 11d3b163175e
Revises: 981f23bc5494
Create Date: 2025-09-26 18:51:24.511840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d3b163175e'
down_revision = '981f23bc5494'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create conversion_files table
    op.create_table('conversion_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversion_files_id'), 'conversion_files', ['id'], unique=False)
    op.create_index(op.f('ix_conversion_files_name'), 'conversion_files', ['name'], unique=False)

    # Create individual_files table
    op.create_table('individual_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversion_file_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('upload_progress', sa.Integer(), nullable=True),
    sa.Column('is_uploaded', sa.Boolean(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversion_file_id'], ['conversion_files.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_individual_files_id'), 'individual_files', ['id'], unique=False)
    op.create_index(op.f('ix_individual_files_name'), 'individual_files', ['name'], unique=False)

    # Create conversion_groups table
    op.create_table('conversion_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('individual_file_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'ERROR', name='conversionstatus'), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('total_outputs', sa.Integer(), nullable=True),
    sa.Column('processed_outputs', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['individual_file_id'], ['individual_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversion_groups_id'), 'conversion_groups', ['id'], unique=False)
    op.create_index(op.f('ix_conversion_groups_name'), 'conversion_groups', ['name'], unique=False)

    # Create conversion_results table
    op.create_table('conversion_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('output_name', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['conversion_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversion_results_id'), 'conversion_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop conversion_results table
    op.drop_index(op.f('ix_conversion_results_id'), table_name='conversion_results')
    op.drop_table('conversion_results')

    # Drop conversion_groups table
    op.drop_index(op.f('ix_conversion_groups_name'), table_name='conversion_groups')
    op.drop_index(op.f('ix_conversion_groups_id'), table_name='conversion_groups')
    op.drop_table('conversion_groups')

    # Drop individual_files table
    op.drop_index(op.f('ix_individual_files_name'), table_name='individual_files')
    op.drop_index(op.f('ix_individual_files_id'), table_name='individual_files')
    op.drop_table('individual_files')

    # Drop conversion_files table
    op.drop_index(op.f('ix_conversion_files_name'), table_name='conversion_files')
    op.drop_index(op.f('ix_conversion_files_id'), table_name='conversion_files')
    op.drop_table('conversion_files')

    # Drop enum
    op.execute('DROP TYPE IF EXISTS conversionstatus')
    # ### end Alembic commands ###