"""Add pdf_created field to jobs table

Revision ID: 6fe9567c652d
Revises: 002_add_vcf_tables
Create Date: 2025-09-26 13:46:40.496966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6fe9567c652d'
down_revision = '002_add_vcf_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_permissions_id', table_name='job_permissions')
    op.drop_table('job_permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_permissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='job_permissions_job_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='job_permissions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='job_permissions_pkey')
    )
    op.create_index('ix_job_permissions_id', 'job_permissions', ['id'], unique=False)
    # ### end Alembic commands ###