"""Add pdf_created field to jobs table

Revision ID: 6fe9567c652d
Revises: 002_add_vcf_tables
Create Date: 2025-09-26 13:46:40.496966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6fe9567c652d'
down_revision = '002_add_vcf_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add pdf_created column to jobs table
    op.add_column('jobs', sa.Column('pdf_created', sa.Boolean(), nullable=True, default=False))

    # Set default value for existing rows
    op.execute("UPDATE jobs SET pdf_created = CASE WHEN output_pdf_path IS NOT NULL AND output_pdf_path != '' THEN true ELSE false END")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove pdf_created column from jobs table
    op.drop_column('jobs', 'pdf_created')
    # ### end Alembic commands ###