"""Add JobPermission model for user access control

Revision ID: 981f23bc5494
Revises: 6fe9567c652d
Create Date: 2025-09-26 15:35:39.369811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981f23bc5494'
down_revision = '6fe9567c652d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###